import type { Metadata } from "next";
import { Oswald, Quattrocento } from "next/font/google";
import "./globals.css";

const oswald = Oswald({ subsets: ["latin"], variable: "--oswald" });
const quattrocento = Quattrocento({ subsets: ["latin"], weight: "400", variable: "--quattrocento" });

export const metadata: Metadata = {
  title: "5 min Study",
  description: "Generated by Max",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quattrocento.variable} ${oswald.variable}`}>
        {children}
      </body>
    </html>
  );
}
