import type { Metadata } from "next";
import { Oswald, Quattrocento } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const oswald = Oswald({ subsets: ["latin"], variable: "--oswald" });
const quattrocento = Quattrocento({ subsets: ["latin"], weight: "400", variable: "--quattrocento" });

export const metadata: Metadata = {
  title: "5 min Study",
  description: "Generated by Max",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quattrocento.variable} ${oswald.variable}`}>
        <Toaster
          position="top-center"
          reverseOrder={false}
        />
        {children}
      </body>
    </html>
  );
}
